### ISSUE TITLE
Defaults from "linchpin init" kinda don't make sense

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#124]
I did a "linchpin init" in a new directory and got the following values in linchpin_config.yml:

```yaml
---
keystore_path: "/home/ghelling/venv/linchpin/lib/python2.7/site-packages/keystore"
outputfolder_path: "/home/ghelling/venv/linchpin/lib/python2.7/site-packages/outputs "
inventoryfolder_path: "/home/ghelling/venv/linchpin/lib/python2.7/site-packages/inventory"
async: False
async_timeout : 1000
no_output : False
schema: "/home/ghelling/venv/linchpin/lib/python2.7/site-packages/ex_schemas/schema_v2.json"
inventory_layouts_path: "/home/ghelling/venv/linchpin/lib/python2.7/site-packages/inventory_layouts"
inventory_outputs_path: "/home/ghelling/venv/linchpin/lib/python2.7/site-packages/inventories"
```

As you see, it's wanting me to put my outputs and inputs inside of my virtualenv site-packages directory instead of locally. It appears the default paths are based from the path to `__file__` instead of `$PWD`.
