### ISSUE TITLE
linchpin rise should not require inventory layout

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#154]
When creating a PinFile, one should be able to list a Pin target without a declared layout.

Currently the following fails:

```
---
libvirt-test:
  topology: simple-libvirt-cluster.yml
```

But 

```
---
libvirt-test:
  topology: simple-libvirt-cluster.yml
  layout: openshift-3node-cluster.yml
```

succeeds. 

The former needs to be allowed. In many cases, a resulting inventory is not desired.
