### ISSUE TITLE
AWS_EC2 fails when the res_grp_vars are not defined

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linch-pin#167]
Example topology : 
```yaml 
---
    topology_name: "ex_aws_topo"
    site: "qeos"
    resource_groups: 
      - 
        resource_group_name: "testgroup1"
        res_group_type: "aws"
        res_defs:
          - 
            res_name: "ha_inst" 
            flavor: "t2.micro"
            res_type: "aws_ec2"
            region: "us-east-1"
            image: "ami-f4cc1de2"
            count: 1
            keypair: "sk_key"
        assoc_creds: "sk_aws_personal"
```
Error : 
```
TASK [aws : Provisioning AWS_EC2 Resource when async == false] *****************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'res_grp_vars' is undefined\n\nThe error appears to have been in '/home/srallaba/.virtualenvs/newenv/lib/python2.7/site-packages/linchpin-0.8.6-py2.7.egg/provision/roles/aws/tasks/provision_aws_ec2.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Provisioning AWS_EC2 Resource when async == false\"\n  ^ here\n"}
        to retry, use: --limit @/home/srallaba/.virtualenvs/newenv/lib/python2.7/site-packages/linchpin-0.8.6-py2.7.egg/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=19   changed=0    unreachable=0    failed=1 
```
