### ISSUE TITLE
(POC) (8) Manage credentials according to the cloud provider

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#76]
Currently, credentials are assigned in the vars of the role. This can obviously be overwritten by global vars or possibly in the linchpin_config.yml. However, many of the cloud providers (openstack, rackspace, aws/ec2, gce) have alternative ways of authenticating with configuration files they already provide.

The rationale here is that users will want to utilize things they already know. It isn't advantageous to add complexity by providing another way to configure credentials. We should provide a way to access the configs that already exist or are already documented.

As an example, check out http://docs.openstack.org/developer/os-client-config/.

**Comment by herlo** [comment]
This is being addressed by a newly designed auth driver. @samvarankashyap, will you provide a basic design concept here in the near future?

**Comment by herlo** [comment]
https://trello.com/c/xd2oh4z3/102-5-ci-provisioning-linch-pin-auth-driver linking in trello card for reference.

**Comment by herlo** [comment]
An update to our topology and command-line functionality essentially came to this example topology:

```yaml
---                                                                                                                                      
    topology_name: "example_topo"                                                                                                        
    site: "qeos"                                                                                                                         
    resource_groups:                                                                                                                     
        credentials:                                                                                                                     
          - profile: e2e-openstack                                                                                                       
          - auth_type: file:secure.yaml                                                                                                  
        res_group_type: "openstack"                                                                                                      
        res_defs:                                                                                                                        
          -                                                                                                                              
            res_name: "ha_inst"                                                                                                          
            flavor: "m1.small"                                                                                                           
            res_type: "os_server"                                                                                                        
            image: "rhel-6.5_jeos"                                                                                                       
            count: 1                                                                                                                     
            keypair: "ci-factory"                                                                                                        
            networks:                                                                                                                    
              - "e2e-openstack"                                                                                                          
      -                                                                                                                                  
        resource_group_name: "testgroup1"                                                                                                
        credentials:                                                                                                                     
          - profile: ec3-awesome                                                                                                         
          - auth_type: file:ec3.ini                                                                                                      
        res_group_type: "aws"                                                                                                            
        res_defs:                                                                                                                        
          -                                                                                                                              
            res_name: "web_inst"                                                                                                         
            flavor: "m1.small"                                                                                                           
            res_type: "ec2"                                                                                                              
            image: "rhel-6.5_jeos"                                                                                                       
            count: 1                                                                                                                     
            keypair: "ci-factory"                                                                                                        
            networks:                                                                                                                    
              - "e2e-openstack" 

```
